### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      Códigos de erro para funções personalizadas. Os códigos de erro aparecerão na célula que chamou a função.

      Mensagens de erro personalizadas aparecem além desses códigos de erro. As mensagens personalizadas são exibidas no menu indicador de erro, que é acessado ao passar o sinalizador de erro em cada célula com um erro.
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: 'Esse código de erro indica que a função usada está sendo dividida por zero ou por células vazias. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: 'Esse código de erro indica que há um erro de digitação no nome da função. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: 'Esse código de erro indica que há um problema com um número na função. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: 'Esse código de erro indica que a função se refere a uma célula inválida. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: 'Esse código de erro indica que um valor na função é do tipo de dados incorreto. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: 'Esse código de erro indica que a função ou serviço não está disponível. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: 'Esse código de erro indica que os intervalos na função não fazem interseção. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'