### YamlMime:UniversalReference
ms.openlocfilehash: 244d32f81364753d62265cdc791e4d8a489e0883
ms.sourcegitcommit: 016e17422cf62dc9f1de1809666e9244e41cc1a9
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 11/09/2018
ms.locfileid: "26228210"
items:
- uid: office.OfficeExtension.Error
  summary: O objeto de erro retornado pela `context.sync()` <!-- -->, se uma promessa é rejeitada devido a um erro ao processar a solicitação.
  name: OfficeExtension.Error
  fullName: OfficeExtension.Error
  langs:
  - typeScript
  type: class
  package: office
  remarks: "\n#### <a name=\"examples\"></a>Exemplos\n\n```javascript\n// Run a batch operation against the Word object model.\nWord.run(function (context) {\n\n    // Create a proxy object for the document body.\n    var body = context.document.body;\n\n    // Queue a commmand to insert text in to the beginning of the body.\n    // This will cause an OfficeExtension.Error.\n    body.insertText(0);\n\n    // Synchronize the document state by executing the queued-up commands,\n    // and return a promise to indicate task completion.\n    return context.sync();\n})\n.catch(function (error) {\n    if (error instanceof OfficeExtension.Error) {\n        console.log('Error code and message: ' + error.toString());\n    }\n});\n```"
  children:
  - office.OfficeExtension.Error.code
  - office.OfficeExtension.Error.debugInfo
  - office.OfficeExtension.Error.innerError
  - office.OfficeExtension.Error.message
  - office.OfficeExtension.Error.name
  - office.OfficeExtension.Error.stack
  - office.OfficeExtension.Error.traceMessages
- uid: office.OfficeExtension.Error.code
  summary: Sequência de código de erro, como "InvalidArgument".
  name: code
  fullName: code
  langs:
  - typeScript
  type: property
  syntax:
    content: 'code: string;'
    return:
      type:
      - string
- uid: office.OfficeExtension.Error.debugInfo
  summary: Depurar info (útil para detalhadas log do erro, ou seja, via `JSON.stringify(...)` <!-- -->).
  name: debugInfo
  fullName: debugInfo
  langs:
  - typeScript
  type: property
  syntax:
    content: 'debugInfo: DebugInfo;'
    return:
      type:
      - office.OfficeExtension.DebugInfo
- uid: office.OfficeExtension.Error.innerError
  summary: Erro interno, se aplicável.
  name: innerError
  fullName: innerError
  langs:
  - typeScript
  type: property
  syntax:
    content: 'innerError: Error;'
    return:
      type:
      - Error
- uid: office.OfficeExtension.Error.message
  summary: A mensagem de erro é passado por meio do host de aplicativos do Office.
  name: message
  fullName: message
  langs:
  - typeScript
  type: property
  syntax:
    content: 'message: string;'
    return:
      type:
      - string
- uid: office.OfficeExtension.Error.name
  summary: 'Nome do erro: "OfficeExtension.Error".'
  name: name
  fullName: name
  langs:
  - typeScript
  type: property
  syntax:
    content: 'name: string;'
    return:
      type:
      - string
- uid: office.OfficeExtension.Error.stack
  summary: A pilha de rastreamento, se aplicável.
  name: stack
  fullName: stack
  langs:
  - typeScript
  type: property
  syntax:
    content: 'stack: string;'
    return:
      type:
      - string
- uid: office.OfficeExtension.Error.traceMessages
  summary: Mensagens de rastreamento (se houver) que foram adicionados por meio de um `context.trace()` invocação antes de chamar `context.sync()` <!-- -->. Se houver um erro, isso contém todas as mensagens de rastreamento que foram executadas antes do erro ocorreu. Essas mensagens podem ajudá-lo a monitorar a sequência de execução do programa e detectar o caso do erro.
  name: traceMessages
  fullName: traceMessages
  langs:
  - typeScript
  type: property
  syntax:
    content: 'traceMessages: string[];'
    return:
      type:
      - string[]
      description: "\n#### <a name=\"examples\"></a>Examples\n\n```javascript\n// The following example shows how you can instrument a batch of commands\n// to determine where an error occurred. The first batch successfully\n// inserts the first two paragraphs into the document and cause no errors.\n// The second batch successfully inserts the third and fourth paragraphs\n// but fails in the call to insert the fifth paragraph. All other commands\n// after the failed command in the batch are not executed, including the\n// command that adds the fifth trace message. In this case, the error\n// occurred after the fourth paragraph was inserted, and before adding the\n// fifth trace message.\n\n// Run a batch operation against the Word object model.\nWord.run(function (context) {\n\n    // Create a proxy object for the document body.\n    var body = context.document.body;\n\n    // Queue a commmand to insert the paragraph at the end of the document body.\n    // Start a batch of commands.\n    body.insertParagraph('1st paragraph', Word.InsertLocation.end);\n    // Queue a command for instrumenting this part of the batch.\n    context.trace('1st paragraph successful');\n\n    body.insertParagraph('2nd paragraph', Word.InsertLocation.end);\n    context.trace('2nd paragraph successful');\n\n    // Synchronize the document state by executing the queued-up commands,\n    // and return a promise to indicate task completion.\n    return context.sync().then(function () {\n        // Queue a commmand to insert the paragraph at the end of the document body.\n        // Start a new batch of commands.\n        body.insertParagraph('3rd paragraph', Word.InsertLocation.end);\n        context.trace('3rd paragraph successful');\n\n        body.insertParagraph('4th paragraph', Word.InsertLocation.end);\n        context.trace('4th paragraph successful');\n\n        // This command will cause an error. The trace messages in the queue up to\n        // this point will be available via Error.traceMessages.\n        body.insertParagraph(0, '5th paragraph', Word.InsertLocation.end);\n        // Queue a command for instrumenting this part of the batch.\n        // This trace message will not be set on Error.traceMessages.\n        context.trace('5th paragraph successful');\n    }).then(context.sync);\n})\n.catch(function (error) {\n    if (error instanceof OfficeExtension.Error) {\n        console.log('Trace messages: ' + error.traceMessages);\n    }\n});\n\n// Output: \"Trace messages: 3rd paragraph successful,4th paragraph successful\"\n```"
